In [33]:
A = [1 2; 3 4; 5 6];
B = [1 2 3; 4 5 6];

C = A * B
C = B' + A
C = A' * B
C = B + A

C =

    9   12   15
   19   26   33
   29   40   51

C =

    2    6
    5    9
    8   12

error: operator *: nonconformant arguments (op1 is 2x3, op2 is 2x3)
error: operator +: nonconformant arguments (op1 is 2x3, op2 is 3x2)


In [34]:
A = [16 2 3 13; 5 11 10 8; 9 7 6 12; 4 14 15 1]

B = A(:, 1:2)
B = A(1:4, 1:2)
B = A(:, 0:2)
B = A(0:4, 0:2)

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1

B =

   16    2
    5   11
    9    7
    4   14

B =

   16    2
    5   11
    9    7
    4   14

error: A(_,0): subscripts must be either integers 1 to (2^63)-1 or logicals
error: A(0,_): subscripts must be either integers 1 to (2^63)-1 or logicals


In [20]:
A = magic(10)
x = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10]

v = zeros(10, 1);
for i = 1:10
  for j = 1:10
    v(i) = v(i) + A(i, j) * x(j);
  end
end
v

v = A * x
v = Ax
v = x' * A
v = sum(A * x)

A =

    92    99     1     8    15    67    74    51    58    40
    98    80     7    14    16    73    55    57    64    41
     4    81    88    20    22    54    56    63    70    47
    85    87    19    21     3    60    62    69    71    28
    86    93    25     2     9    61    68    75    52    34
    17    24    76    83    90    42    49    26    33    65
    23     5    82    89    91    48    30    32    39    66
    79     6    13    95    97    29    31    38    45    72
    10    12    94    96    78    35    37    44    46    53
    11    18   100    77    84    36    43    50    27    59

x =

    1
    2
    3
    4
    5
    6
    7
    8
    9
   10

v =

   2650
   2680
   2940
   2680
   2650
   2825
   2855
   2815
   2855
   2825

v =

   2650
   2680
   2940
   2680
   2650
   2825
   2855
   2815
   2855
   2825

error: 'Ax' undefined near line 1 column 5
v =

   2165   1830   3460   3705   3665   2415   2455   2585   2455   3040

v =  27775


In [35]:
v = [1; 2; 3; 4; 5; 6; 7]
w = [7; 6; 5; 4; 3; 2; 1]

z = 0;
for i = 1:7
  z = z + v(i) * w(i);
end
z

z = sum(v .* w)
z = w' * v
z = v * w'
z = w * v'

v =

   1
   2
   3
   4
   5
   6
   7

w =

   7
   6
   5
   4
   3
   2
   1

z =  84
z =  84
z =  84
z =

    7    6    5    4    3    2    1
   14   12   10    8    6    4    2
   21   18   15   12    9    6    3
   28   24   20   16   12    8    4
   35   30   25   20   15   10    5
   42   36   30   24   18   12    6
   49   42   35   28   21   14    7

z =

    7   14   21   28   35   42   49
    6   12   18   24   30   36   42
    5   10   15   20   25   30   35
    4    8   12   16   20   24   28
    3    6    9   12   15   18   21
    2    4    6    8   10   12   14
    1    2    3    4    5    6    7



In [37]:
X = magic(7)

for i = 1:7
  for j = 1:7
    A(i, j) = log(X(i, j));
    B(i, j) = X(i, j) ^ 2;
    C(i, j) = X(i, j) + 1;
    D(i, j) = X(i, j) / 4;
  end
end

A

A = log(X)

B

B = X .^ 2
B = X ^ 2

C

C = X + 1

D

D = X ./ 4
D = X / 4

X =

   30   39   48    1   10   19   28
   38   47    7    9   18   27   29
   46    6    8   17   26   35   37
    5   14   16   25   34   36   45
   13   15   24   33   42   44    4
   21   23   32   41   43    3   12
   22   31   40   49    2   11   20

A =

   3.40120   3.66356   3.87120   0.00000   2.30259   2.94444   3.33220
   3.63759   3.85015   1.94591   2.19722   2.89037   3.29584   3.36730
   3.82864   1.79176   2.07944   2.83321   3.25810   3.55535   3.61092
   1.60944   2.63906   2.77259   3.21888   3.52636   3.58352   3.80666
   2.56495   2.70805   3.17805   3.49651   3.73767   3.78419   1.38629
   3.04452   3.13549   3.46574   3.71357   3.76120   1.09861   2.48491
   3.09104   3.43399   3.68888   3.89182   0.69315   2.39790   2.99573

A =

   3.40120   3.66356   3.87120   0.00000   2.30259   2.94444   3.33220
   3.63759   3.85015   1.94591   2.19722   2.89037   3.29584   3.36730
   3.82864   1.79176   2.07944   2.83321   3.25810   3.55535   3.61092
   1.60944   2.63906 